// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG6NsWogPHgqGzSgEkCscb9yf6kb-epMQ',
    appId: '1:35707398349:web:83eff4a39eac309b3fe184',
    messagingSenderId: '35707398349',
    projectId: 'laboratory2-19376',
    authDomain: 'laboratory2-19376.firebaseapp.com',
    storageBucket: 'laboratory2-19376.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlLy2L1oZhv1_nQBQ0JzqjUcDGtFIgoxA',
    appId: '1:35707398349:android:a2baf166c2ed98ca3fe184',
    messagingSenderId: '35707398349',
    projectId: 'laboratory2-19376',
    storageBucket: 'laboratory2-19376.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAanMdDrghFlFrCK9-FcMKjkVNA_A-hIc',
    appId: '1:35707398349:ios:55e6e40eea48cf4f3fe184',
    messagingSenderId: '35707398349',
    projectId: 'laboratory2-19376',
    storageBucket: 'laboratory2-19376.firebasestorage.app',
    iosBundleId: 'com.finki.lab2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAanMdDrghFlFrCK9-FcMKjkVNA_A-hIc',
    appId: '1:35707398349:ios:55e6e40eea48cf4f3fe184',
    messagingSenderId: '35707398349',
    projectId: 'laboratory2-19376',
    storageBucket: 'laboratory2-19376.firebasestorage.app',
    iosBundleId: 'com.finki.lab2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBG6NsWogPHgqGzSgEkCscb9yf6kb-epMQ',
    appId: '1:35707398349:web:7ae61bbbb2ad73333fe184',
    messagingSenderId: '35707398349',
    projectId: 'laboratory2-19376',
    authDomain: 'laboratory2-19376.firebaseapp.com',
    storageBucket: 'laboratory2-19376.firebasestorage.app',
  );
}
